import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('login não exibe exemplos ou códigos corporativos reais', () => {
  const source = read('src/LoginPage.tsx')
  assert.doesNotMatch(source, /m0043497/i)
  assert.doesNotMatch(source, /@ems\.com\.br/i)
})

test('SIP destaca sem combate, projeção e CNPJs com vendas', () => {
  const view = read('src/SipDetailView.tsx')
  const api = read('functions/api/sips/detalhe.js')
  const commercial = read('functions/_lib/commercial.js')
  assert.match(view, /CNPJs com vendas/)
  assert.match(view, /OL Sem Combate/)
  assert.match(view, /Projeção/)
  assert.match(view, /Notas faturadas/)
  assert.match(view, /Não faturados por consultor/)
  assert.match(view, /valor_a_faturar/)
  assert.match(view, /OL Total/)
  assert.match(api, /projecao_ol_sem_combate/)
  assert.match(api, /projecao_meta/)
  assert.match(commercial, /total_atendido_sem_imposto/)
  assert.match(commercial, /valor_total_solicitado_sem_imposto/)
})

test('Mercado Farma usa buybox suspenso e Excel xlsx real por UF', () => {
  const market = read('src/MarketFarmaModule.new.tsx')
  const workflow = read('../.github/workflows/mercadofarma.yml')
  const download = read('functions/api/mercado-farma-excel.js')
  assert.match(market, /mef-product-card/)
  assert.match(market, /mef-buybox-menu/)
  assert.match(market, /aria-expanded=\{menuOpen\}/)
  assert.match(market, /\/api\/mercado-farma-excel/)
  assert.match(market, /Atualizar Mercado Farma/)
  assert.doesNotMatch(market, /Atualizar tela/)
  assert.match(download, /application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet/)
  assert.match(download, /mercado-farma-por-estado\.xlsx/)
  assert.match(workflow, /mercadofarma_consolidado\.xlsx web\/public\/exports\/mercadofarma\.xlsx/)
  assert.match(workflow, /Sincronizar consolidado no D1/)
})

test('ranking usa código do setor em vez da UF do consultor', () => {
  const view = read('src/ConsultantsModule.tsx')
  const api = read('functions/api/consultores.js')
  assert.match(view, /Setor \{consultant\.setor/)
  assert.doesNotMatch(view, /consultant\.uf\|\|/)
  for (const setor of ['18150300','18150301','18150302','18150303','18150304','18150305']) assert.match(api, new RegExp(setor))
})

test('pedidos ficam dentro do card expansível de cada consultor', () => {
  const app = read('src/App.tsx')
  const legacy = read('src/PendingOrdersOverview.tsx')
  const view = read('src/ConsultantsModule.tsx')
  const api = read('functions/api/consultor-pedidos.js')
  assert.match(legacy, /return null/)
  assert.match(app, /PendingOrdersOverview/)
  assert.match(view, /aria-expanded=\{isExpanded\}/)
  assert.match(view, /Atendidos? e ainda não faturados?/)
  assert.match(view, /Pedidos faturados/)
  assert.match(view, /Pedidos ainda não faturados/)
  assert.match(view, /Baixar detalhes/)
  assert.match(view, /\/api\/consultor-pedidos/)
  assert.match(view, /text\/csv/)
  assert.match(api, /valor_considerado/)
  assert.match(api, /PEDIDO_NAO_FATURADO/)
})

test('conflitos da auditoria são clicáveis e possuem motivo', () => {
  const view = read('src/CalculationAudit.tsx')
  const details = read('functions/api/admin/auditoria-detalhes.js')
  assert.match(view, /Abrir detalhes/)
  assert.match(view, /itens_sem_classificacao/)
  assert.match(details, /Produtos sem classificação/)
  assert.match(details, /motivo/)
  assert.match(details, /ean/)
  assert.match(details, /produto/)
})

test('navegação persiste a página na URL e oferece saída visível', () => {
  const shell = read('src/AppShell.tsx')
  const app = read('src/App.tsx')
  const navigation = read('src/navigation.ts')
  const styles = read('src/session-controls.css')
  assert.match(navigation, /searchParams\.set\('pagina'/)
  assert.match(navigation, /history\[method\]/)
  assert.match(shell, /addEventListener\('popstate'/)
  assert.match(shell, /savePageInHistory\('dashboard', true\)/)
  assert.match(app, /onNavigate\(nextPage\)/)
  assert.match(app, />Sair<\/button>/)
  assert.match(shell, />Sair<\/button>/)
  assert.match(styles, /\.topbar-logout/)
})
