import { useEffect, useMemo, useState } from 'react'
import './desafio-gigantes-card.css'

type Produto = { sku:string; produto:string; ean:string; meta_positivacao:number; meta_giro:number; positivacao_real:number; giro_real:number; atingimento_positivacao:number; atingimento_giro:number; pontos_estimados:number; falta_pdv_80:number }
type Resumo = { ano_mes:string; colaborador:string; metas:number; skus:number; identificados:number; pos_80:number; giro_80:number; pontuacao_estimada:number; maximo_estimado:number; identificacao?:{total:number;identificados:number;pendentes:number;ambiguos:number;nao_encontrados:number;erros:number}; oportunidades:Produto[]; aviso?:string; erro?:string; detalhe?:string }
type Props = { inicio:string; consultor:string; uf:string }
const vazio:Resumo={ano_mes:'',colaborador:'',metas:0,skus:0,identificados:0,pos_80:0,giro_80:0,pontuacao_estimada:0,maximo_estimado:0,oportunidades:[]}
const pct=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})
const num=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1})
const mes=(v:string)=>/^\d{4}-\d{2}$/.test(v)?`${v.slice(5,7)}/${v.slice(0,4)}`:v

export default function DesafioGigantesCard({inicio,consultor,uf}:Props){
  const [data,setData]=useState<Resumo>(vazio),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const anoMes=useMemo(()=>/^\d{4}-\d{2}/.test(inicio||'')?inicio.slice(0,7):'', [inicio])
  useEffect(()=>{const c=new AbortController();setLoading(true);setError('');const p=new URLSearchParams();if(anoMes)p.set('ano_mes',anoMes);if(consultor)p.set('consultor',consultor);if(uf)p.set('uf',uf);fetch(`/api/desafio-gigantes?${p}`,{cache:'no-store',signal:c.signal}).then(async r=>{const b=await r.json() as Resumo;if(!r.ok)throw new Error(b.detalhe||b.erro||'Falha ao carregar campanha');setData(b)}).catch(e=>{if(!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:String(e))}).finally(()=>setLoading(false));return()=>c.abort()},[anoMes,consultor,uf])
  const pend=(data.identificacao?.pendentes||0)+(data.identificacao?.ambiguos||0)+(data.identificacao?.nao_encontrados||0)+(data.identificacao?.erros||0)
  const foco=data.oportunidades?.[0]
  const alcance=data.maximo_estimado>0?data.pontuacao_estimada/data.maximo_estimado*100:0
  return <section className="dg-card"><div className="dg-heading"><div><span>🏆 CAMPANHA</span><h2>Desafio de Gigantes</h2><p>{data.colaborador||'Equipe Norte'} · {mes(data.ano_mes||anoMes)} · parcial gerencial</p></div><b>CDD / Close-Up oficial</b></div>{error&&<div className="dg-alert">{error}</div>}{loading?<div className="dg-loading">Atualizando campanha…</div>:data.metas===0?<div className="dg-empty"><strong>Card ativo</strong><span>Não há metas para este período. Importe a planilha na Administração.</span></div>:<><div className="dg-metrics"><div className="score"><span>Pontuação estimada</span><strong>{num.format(data.pontuacao_estimada)}</strong><small>{pct.format(alcance)}% do máximo gerencial</small></div><div><span>SKUs da meta</span><strong>{data.skus}</strong><small>{data.identificados} identificados</small></div><div><span>Positivação ≥80%</span><strong>{data.pos_80}/{data.skus}</strong><small>{pct.format(data.skus?data.pos_80/data.skus*100:0)}%</small></div><div><span>Giro ≥80%</span><strong>{data.giro_80}/{data.skus}</strong><small>{pct.format(data.skus?data.giro_80/data.skus*100:0)}%</small></div><div><span>Mercado Farma</span><strong>{pend?`${pend} pend.`:'OK'}</strong><small>{data.identificacao?.identificados||0}/{data.identificacao?.total||data.skus} SAPs</small></div></div><div className="dg-action"><div><span>Próximo melhor movimento</span>{foco?<><strong>{foco.produto}</strong><small>SAP {foco.sku} · faltam {foco.falta_pdv_80} PDV(s) para 80% da positivação.</small></>:<><strong>Manter acompanhamento</strong><small>Sem SKU identificado abaixo de 80% neste recorte.</small></>}</div>{foco&&<div><b>{foco.positivacao_real}/{num.format(foco.meta_positivacao)}</b><span> · {pct.format(foco.atingimento_positivacao)}%</span></div>}</div>{data.oportunidades?.length>0&&<details className="dg-details"><summary>Ver produtos que precisam de ação</summary><div className="dg-table"><table><thead><tr><th>SAP</th><th>Produto</th><th>Positivação</th><th>Giro</th><th>Pontos</th></tr></thead><tbody>{data.oportunidades.map(i=><tr key={`${i.sku}-${i.ean}`}><td>{i.sku}</td><td>{i.produto}</td><td>{i.positivacao_real}/{num.format(i.meta_positivacao)} · {pct.format(i.atingimento_positivacao)}%</td><td>{num.format(i.giro_real)}/{num.format(i.meta_giro)} · {pct.format(i.atingimento_giro)}%</td><td>{num.format(i.pontos_estimados)}</td></tr>)}</tbody></table></div></details>}<p className="dg-note">{data.aviso}</p></>}</section>
}
