import { useEffect, useMemo, useState } from 'react'
import DesafioGigantesCard from './DesafioGigantesCard'
import './operations.css'
import './desafio-gigantes-module.css'

type Consultor = { consultor_id:string; nome_colaborador:string; setor:string; skus:number; identificados:number; pos_80:number; giro_80:number; pontuacao_estimada:number; maximo_estimado:number }
type SapProblema = { sku:string; status:string; ean:string; produto:string; produto_planilha:string; mensagem:string; tentativas:number; ultima_consulta_em:string }
type Visao = { ano_mes:string; identificacao?:{total:number;identificados:number;pendentes:number;ambiguos:number;nao_encontrados:number;erros:number;ultima_consulta_em?:string}; consultores?:Consultor[]; saps_problema?:SapProblema[]; erro?:string; detalhe?:string }
type Correcao = { ean:string; produto:string }

const num=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1})
const pct=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:0,maximumFractionDigits:1})
const mesAtual=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const dataHora=(value:string)=>{if(!value)return 'Ainda não consultado';const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(d)}
const statusLabel=(value:string)=>({PENDENTE:'Pendente',AMBIGUO:'Ambíguo',NAO_ENCONTRADO:'Não encontrado',ERRO:'Erro',IDENTIFICADO:'Identificado'} as Record<string,string>)[value]||value||'Pendente'

export default function DesafioGigantesModule({onBack}:{onBack:()=>void}){
  const [anoMes,setAnoMes]=useState(mesAtual()),[consultor,setConsultor]=useState(''),[data,setData]=useState<Visao>({ano_mes:mesAtual(),consultores:[],saps_problema:[]})
  const [correcoes,setCorrecoes]=useState<Record<string,Correcao>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[version,setVersion]=useState(0)
  async function load(){setLoading(true);setError('');try{const r=await fetch(`/api/desafio-gigantes?ano_mes=${encodeURIComponent(anoMes)}`,{cache:'no-store'});const b=await r.json() as Visao;if(!r.ok)throw new Error(b.detalhe||b.erro||'Não foi possível carregar o Desafio de Gigantes.');setData(b);setCorrecoes(current=>{const next={...current};for(const item of b.saps_problema||[])if(!next[item.sku])next[item.sku]={ean:item.ean||'',produto:item.produto_planilha||item.produto||''};return next})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[anoMes])
  const pendentes=useMemo(()=>{const i=data.identificacao;return(i?.pendentes||0)+(i?.ambiguos||0)+(i?.nao_encontrados||0)+(i?.erros||0)},[data.identificacao])
  async function corrigir(item:SapProblema){const values=correcoes[item.sku]||{ean:'',produto:item.produto_planilha||''};const ean=values.ean.replace(/\D/g,'');if(ean.length<8||ean.length>14){setError(`Informe um EAN válido para o SAP ${item.sku}.`);return}setBusy(item.sku);setError('');setMessage('');try{const r=await fetch('/api/desafio-gigantes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({acao:'corrigir_sap',sku:item.sku,ean,produto:values.produto})});const b=await r.json();if(!r.ok)throw new Error(b.detalhe||b.erro||'Não foi possível corrigir o SAP.');setMessage(`SAP ${item.sku} corrigido e vinculado ao EAN ${ean}.`);await load();setVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  async function verificarAgora(){setBusy('verificar');setError('');setMessage('');try{const r=await fetch('/api/desafio-gigantes-disparar',{method:'POST'});const b=await r.json();if(!r.ok)throw new Error(b.detalhe||b.erro||'Não foi possível acionar a verificação.');setMessage('Verificação dos SAPs acionada no Mercado Farma. Os resultados serão atualizados quando a execução terminar.')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  return <main className="content operations-page dg-page">
    <button className="back-button" type="button" onClick={onBack}>← Voltar ao painel</button>
    <section className="operations-hero dg-hero"><div><span className="eyebrow">Campanha comercial</span><h1>🏆 Desafio de Gigantes</h1><p>Acompanhe metas, positivação, giro e pontuação por consultor. Os SAPs sem identificação ficam visíveis para correção.</p></div><div className="dg-hero-actions"><label><span>Mês da campanha</span><input type="month" value={anoMes} onChange={e=>setAnoMes(e.target.value)}/></label><button className="secondary-button" type="button" disabled={busy==='verificar'} onClick={()=>void verificarAgora()}>{busy==='verificar'?'Acionando…':'Verificar SAPs agora'}</button></div></section>
    {error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-success">{message}</div>}
    <section className="dg-status-strip"><div><span>SAPs da campanha</span><strong>{data.identificacao?.total||0}</strong></div><div><span>Identificados</span><strong>{data.identificacao?.identificados||0}</strong></div><div className={pendentes?'warning':'ok'}><span>Precisam de atenção</span><strong>{pendentes}</strong></div><div><span>Última consulta</span><strong>{dataHora(data.identificacao?.ultima_consulta_em||'')}</strong></div></section>
    <section className="dg-section-heading"><div><span className="eyebrow">Equipe Norte</span><h2>Consultores</h2></div>{consultor&&<button className="secondary-button" type="button" onClick={()=>setConsultor('')}>Ver consolidado GD</button>}</section>
    <section className="dg-consultants-grid">{(data.consultores||[]).map(item=>{const alcance=item.maximo_estimado>0?item.pontuacao_estimada/item.maximo_estimado*100:0;const active=consultor===item.consultor_id;return <button type="button" className={`dg-consultant-card ${active?'active':''}`} key={item.consultor_id} onClick={()=>setConsultor(active?'':item.consultor_id)}><div><span>Setor {item.setor||'—'}</span><b>{item.nome_colaborador}</b></div><strong>{num.format(item.pontuacao_estimada)} pts</strong><small>{pct.format(alcance)}% do máximo gerencial</small><div className="dg-consultant-stats"><span>Pos. ≥80% <b>{item.pos_80}/{item.skus}</b></span><span>Giro ≥80% <b>{item.giro_80}/{item.skus}</b></span><span>EAN <b>{item.identificados}/{item.skus}</b></span></div></button>})}{!loading&&!(data.consultores||[]).length&&<div className="dg-no-data">Nenhum consultor encontrado na meta de {anoMes}.</div>}</section>
    <DesafioGigantesCard key={`${anoMes}-${consultor}-${version}`} inicio={`${anoMes}-01`} consultor={consultor} uf=""/>
    <section className="dg-section-heading dg-errors-title"><div><span className="eyebrow">Conferência SAP → EAN</span><h2>SAPs que precisam de correção</h2><p>Quando o Mercado Farma retorna resultado ambíguo, o sistema não escolhe um EAN no chute. Corrija abaixo.</p></div><b className={pendentes?'dg-problem-count':'dg-ok-count'}>{pendentes?`${pendentes} pendente(s)`:'Tudo certo'}</b></section>
    {loading?<div className="dg-no-data">Carregando conferência dos SAPs…</div>:(data.saps_problema||[]).length===0?<div className="dg-all-ok"><strong>✓ Todos os SAPs estão identificados</strong><span>Não há correções manuais pendentes para este mês.</span></div>:<div className="dg-correction-list">{(data.saps_problema||[]).map(item=>{const values=correcoes[item.sku]||{ean:item.ean||'',produto:item.produto_planilha||item.produto||''};return <article className="dg-correction-card" key={item.sku}><div className="dg-correction-info"><div><span className={`dg-status dg-status-${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span><strong>SAP {item.sku}</strong></div><b>{item.produto_planilha||item.produto||'Produto não identificado'}</b><p>{item.mensagem||'Sem detalhe da consulta.'}</p><small>{item.tentativas||0} tentativa(s) · {dataHora(item.ultima_consulta_em)}</small></div><div className="dg-correction-form"><label><span>EAN correto</span><input inputMode="numeric" placeholder="Digite o EAN" value={values.ean} onChange={e=>setCorrecoes(c=>({...c,[item.sku]:{...values,ean:e.target.value}}))}/></label><label><span>Produto</span><input placeholder="Nome do produto" value={values.produto} onChange={e=>setCorrecoes(c=>({...c,[item.sku]:{...values,produto:e.target.value}}))}/></label><button className="primary-button" type="button" disabled={busy===item.sku} onClick={()=>void corrigir(item)}>{busy===item.sku?'Salvando…':'Salvar correção'}</button></div></article>})}</div>}
  </main>
}
