import readXlsxFile from'read-excel-file'
export type HistoryRecord={ano_mes:string;cnpj:string;faturamento:number;pedidos:number;produtos:number;quantidade:number}
const norm=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'')
const digits=(v:unknown)=>String(v??'').replace(/\D/g,'')
const num=(v:unknown)=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/R\$|\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replaceAll('.','').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function month(v:unknown){if(v instanceof Date&&!isNaN(v.getTime()))return`${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}`;if(typeof v==='number'&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`};const s=String(v??'').trim();let m=s.match(/^(\d{4})[-\/]?(\d{2})/);if(m)return`${m[1]}-${m[2]}`;m=s.match(/^(\d{1,2})[\/]\d{1,2}[\/](\d{4})/);if(m)return`${m[2]}-${String(Number(m[1])).padStart(2,'0')}`;m=s.match(/^(\d{1,2})[\/](\d{4})$/);return m?`${m[2]}-${String(Number(m[1])).padStart(2,'0')}`:''}
function csvRows(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),sep=(lines[0]?.match(/;/g)||[]).length>=(lines[0]?.match(/,/g)||[]).length?';':',';return lines.map(line=>{const out:string[]=[],re=new RegExp(`(?:^|${sep})(?:"([^"]*(?:""[^"]*)*)"|([^${sep}]*))`,'g');let match;while((match=re.exec(line)))out.push((match[1]??match[2]??'').replaceAll('""','"'));return out})}
const find=(headers:string[],names:string[])=>headers.findIndex(h=>names.includes(h))
export async function parseHistoryFile(file:File){const rows=file.name.toLowerCase().endsWith('.csv')?csvRows(await file.text()):await readXlsxFile(file);if(rows.length<2)throw new Error('A planilha não possui linhas para importar.');const headers=rows[0].map(norm),iCnpj=find(headers,['CNPJ','CNPJ_PDV','CNPJ_CLIENTE','DOCUMENTO']),iMonth=find(headers,['ANO_MES','MES','MES_ANO','COMPETENCIA']),iDate=find(headers,['DATA_DE_FATURAMENTO','DATA_FATURAMENTO','DATA_DO_PEDIDO','DATA_PEDIDO','DATA']),iValue=find(headers,['VALOR_FATURADO','FATURAMENTO','VALOR','OL_TOTAL']),iOrder=find(headers,['PEDIDO_ID','PEDIDO','NUMERO_PEDIDO','PEDIDOS']),iProduct=find(headers,['EAN','PRODUTO','SKU_PRODUTO','CODIGO_PRODUTO','PRODUTOS']),iQty=find(headers,['QUANTIDADE_FATURADA','QUANTIDADE','QTD_FATURADA','QTD']);if(iCnpj<0||iMonth<0&&iDate<0)throw new Error('Não localizei as colunas de CNPJ e mês/data.');const map=new Map<string,{ano_mes:string;cnpj:string;faturamento:number;quantidade:number;orders:Set<string>;products:Set<string>;pedidosInformados:number;produtosInformados:number}>();let ignored=0;for(const row of rows.slice(1)){const cnpj=digits(row[iCnpj]);const ano_mes=month(iMonth>=0?row[iMonth]:row[iDate]);if(cnpj.length!==14||!ano_mes){ignored++;continue}const key=`${ano_mes}|${cnpj}`;if(!map.has(key))map.set(key,{ano_mes,cnpj,faturamento:0,quantidade:0,orders:new Set(),products:new Set(),pedidosInformados:0,produtosInformados:0});const item=map.get(key)!;item.faturamento+=iValue>=0?num(row[iValue]):0;item.quantidade+=iQty>=0?num(row[iQty]):0;if(iOrder>=0){const value=String(row[iOrder]??'').trim();if(value)item.orders.add(value);if(headers[iOrder]==='PEDIDOS')item.pedidosInformados=Math.max(item.pedidosInformados,num(row[iOrder]))}if(iProduct>=0){const value=String(row[iProduct]??'').trim();if(value)item.products.add(value);if(headers[iProduct]==='PRODUTOS')item.produtosInformados=Math.max(item.produtosInformados,num(row[iProduct]))}}const registros:HistoryRecord[]=[...map.values()].map(x=>({ano_mes:x.ano_mes,cnpj:x.cnpj,faturamento:Number(x.faturamento.toFixed(2)),quantidade:x.quantidade,pedidos:Math.max(x.orders.size,x.pedidosInformados),produtos:Math.max(x.products.size,x.produtosInformados)}));if(!registros.length)throw new Error('Nenhum registro válido foi encontrado na planilha.');return{registros,linhas:rows.length-1,ignoradas:ignored,meses:new Set(registros.map(x=>x.ano_mes)).size}}
