import {useEffect,useMemo,useState} from 'react'
import './operations.css'

type Item={id:string;ano_mes:string;escopo:string;referencia_id:string;referencia_nome:string;versao:number;fechado_em:string;resultado:Record<string,any>}
type Data={meses:Array<{ano_mes:string;fechado_em:string;versao:number}>;geral:Item[];itens:Item[];aviso?:string}
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),num=new Intl.NumberFormat('pt-BR'),pct=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})
const month=(v:string)=>{const[y,m]=String(v||'').split('-');return y&&m?`${m}/${y}`:v}
const value=(x:any,k:string)=>Number(x?.resultado?.[k]||0)
export default function HistoryModule({onBack,onAutomations}:{onBack:()=>void;onAutomations:()=>void}){
 const [data,setData]=useState<Data>({meses:[],geral:[],itens:[]}),[selected,setSelected]=useState(''),[scope,setScope]=useState('CONSULTOR'),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{const controller=new AbortController();async function load(){setLoading(true);setError('');try{const r=await fetch('/api/historico',{cache:'no-store',signal:controller.signal}),d=await r.json();if(!r.ok)throw new Error(d.detalhe||d.erro||'Falha ao carregar histórico');setData(d);setSelected(x=>x||d.meses?.[0]?.ano_mes||'')}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}void load();return()=>controller.abort()},[])
 const current=useMemo(()=>data.geral.find(x=>x.ano_mes===selected),[data,selected]),previous=useMemo(()=>{const ordered=[...data.geral].sort((a,b)=>b.ano_mes.localeCompare(a.ano_mes)),i=ordered.findIndex(x=>x.ano_mes===selected);return i>=0?ordered[i+1]:undefined},[data,selected]),rows=data.itens.filter(x=>x.ano_mes===selected&&x.escopo===scope)
 const variation=(key:string)=>{const a=value(current,key),b=value(previous,key);return b>0?(a-b)/b*100:a>0?100:0}
 const metrics=[['OL total','ol_total'],['OL sem combate','ol_sem_combate'],['Prioritários','ol_prioritarios'],['Lançamentos','ol_lancamentos']]
 return <main className="content operations-page"><button className="back-button" onClick={onBack}>← Voltar ao painel</button><section className="operations-hero"><div><span className="eyebrow">Fotografias permanentes</span><h1>Histórico mensal</h1><p>Resultados e metas ficam guardados por mês, sem serem alterados por extrações futuras.</p></div><button className="secondary-button" onClick={onAutomations}>Executar fechamento</button></section>
 {error&&<div className="alert alert-error">{error}</div>}{data.aviso&&<div className="alert alert-error">{data.aviso}</div>}
 <section className="filters history-filters"><label><span>Mês fechado</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione</option>{data.meses.map(x=><option key={x.ano_mes} value={x.ano_mes}>{month(x.ano_mes)} · versão {x.versao}</option>)}</select></label><label><span>Detalhamento</span><select value={scope} onChange={e=>setScope(e.target.value)}><option value="CONSULTOR">Consultores</option><option value="GD">GD / Gerente</option><option value="UF">UF</option><option value="SIP">SIP</option></select></label></section>
 {!selected&&!loading?<div className="history-empty"><h2>Nenhum mês fechado</h2><p>Use a Central de Automações para fechar um mês. Depois, os resultados aparecerão aqui.</p></div>:<><section className="history-summary">{metrics.map(([label,key])=><article key={key}><span>{label}</span><strong>{loading?'—':money.format(value(current,key))}</strong><small className={variation(key)<0?'variation-negative':'variation-positive'}>{variation(key)>=0?'+':''}{pct.format(variation(key))}% versus {month(previous?.ano_mes||'mês anterior')}</small></article>)}<article><span>Clientes com venda</span><strong>{num.format(value(current,'clientes_com_venda'))}</strong><small>{num.format(value(current,'clientes_sem_venda'))} sem venda · {pct.format(value(current,'positivacao_percentual'))}%</small></article><article><span>Resultado da meta</span><strong>{pct.format(value(current,'resultado_meta_ol'))}%</strong><small>Meta: {money.format(value(current,'meta_ol_sem_combate'))}</small></article></section>
 <section className="operations-list"><div className="operations-heading"><h2>Resultado por {scope==='CONSULTOR'?'consultor':scope==='GD'?'GD':scope}</h2><span>{rows.length} registros</span></div>{!rows.length?<div className="operations-empty">Sem detalhamento para esse mês.</div>:<div className="history-table-wrap"><table className="history-table"><thead><tr><th>Referência</th><th>OL total</th><th>Sem combate</th><th>Prioritários</th><th>Lançamentos</th><th>Clientes</th><th>Positivação</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.referencia_nome||x.referencia_id}</strong></td><td>{money.format(value(x,'ol_total'))}</td><td>{money.format(value(x,'ol_sem_combate'))}</td><td>{money.format(value(x,'ol_prioritarios'))}</td><td>{money.format(value(x,'ol_lancamentos'))}</td><td>{num.format(value(x,'clientes_com_venda'))}/{num.format(value(x,'clientes_ativos'))}</td><td>{pct.format(value(x,'positivacao_percentual'))}%</td></tr>)}</tbody></table></div>}</section></>}</main>
}
