import {useEffect,useState} from 'react'
import './operations.css'

type Row={uf:string;ean:string;produto:string;distribuidora:string;estoque:number;desconto:number;preco_com_imposto:number;preco_sem_imposto:number;melhor_preco:number|null;status:string;erro:string;atualizado_em:string}
type Data={resumo:{registros:number;produtos:number;ufs:number;distribuidoras:number;com_estoque:number;atualizado_em:string|null};resultados:Row[];filtros:{ufs:string[];distribuidoras:string[]};ultima_extracao:any}
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),num=new Intl.NumberFormat('pt-BR')
const date=(v:string|null|undefined)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('pt-BR')}
export default function MarketFarmaModule({onBack,onAutomations}:{onBack:()=>void;onAutomations:()=>void}){
 const [uf,setUf]=useState(''),[dist,setDist]=useState(''),[search,setSearch]=useState(''),[stock,setStock]=useState(false),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{const controller=new AbortController(),timer=window.setTimeout(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams({limite:'500'});if(uf)p.set('uf',uf);if(dist)p.set('distribuidora',dist);if(search)p.set('busca',search);if(stock)p.set('estoque','1');const r=await fetch(`/api/mercado-farma?${p}`,{cache:'no-store',signal:controller.signal}),d=await r.json();if(!r.ok)throw new Error(d.detalhe||d.erro||'Falha ao carregar Mercado Farma');setData(d)}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},search?300:0);return()=>{controller.abort();window.clearTimeout(timer)}},[uf,dist,search,stock])
 const r=data?.resumo
 return <main className="content operations-page"><button className="back-button" onClick={onBack}>← Voltar ao painel</button><section className="operations-hero"><div><span className="eyebrow">Preços e estoques</span><h1>Mercado Farma</h1><p>Compare produtos, distribuidores, estoque disponível e o menor preço por UF.</p></div><button className="secondary-button" onClick={onAutomations}>Extrair agora</button></section>
 <section className="filters market-filters"><label><span>UF</span><select value={uf} onChange={e=>setUf(e.target.value)}><option value="">Todas</option>{(data?.filtros.ufs||[]).map(x=><option key={x}>{x}</option>)}</select></label><label><span>Distribuidora</span><select value={dist} onChange={e=>setDist(e.target.value)}><option value="">Todas</option>{(data?.filtros.distribuidoras||[]).map(x=><option key={x}>{x}</option>)}</select></label><label className="market-search"><span>Produto ou EAN</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar"/></label><label className="stock-check"><input type="checkbox" checked={stock} onChange={e=>setStock(e.target.checked)}/><span>Somente com estoque</span></label></section>
 {error&&<div className="alert alert-error">{error}</div>}
 <section className="market-summary"><article><span>Produtos</span><strong>{loading?'—':num.format(r?.produtos||0)}</strong></article><article><span>Registros</span><strong>{loading?'—':num.format(r?.registros||0)}</strong></article><article><span>Com estoque</span><strong>{loading?'—':num.format(r?.com_estoque||0)}</strong></article><article><span>Última atualização</span><strong className="market-date">{date(r?.atualizado_em)}</strong></article></section>
 <section className="operations-list"><div className="operations-heading"><h2>Comparativo de preços</h2><span>{num.format(data?.resultados.length||0)} linhas exibidas</span></div><div className="market-table-wrap"><table className="market-table"><thead><tr><th>Produto</th><th>UF</th><th>Distribuidora</th><th>Estoque</th><th>Preço s/ imposto</th><th>Preço c/ imposto</th><th>Melhor preço</th><th>Atualização</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="operations-empty">Carregando preços…</td></tr>:!data?.resultados.length?<tr><td colSpan={8} className="operations-empty">Nenhum resultado encontrado.</td></tr>:data.resultados.map((x,i)=><tr key={`${x.uf}-${x.ean}-${x.distribuidora}-${i}`}><td><strong>{x.produto||'Produto sem descrição'}</strong><small>{x.ean}</small></td><td>{x.uf}</td><td>{x.distribuidora}</td><td><b className={x.estoque>0?'stock-positive':'stock-zero'}>{num.format(x.estoque)}</b></td><td>{money.format(x.preco_sem_imposto)}</td><td>{money.format(x.preco_com_imposto)}</td><td><strong className={x.melhor_preco!==null&&Math.abs(x.preco_sem_imposto-x.melhor_preco)<0.001?'best-price':''}>{x.melhor_preco===null?'—':money.format(x.melhor_preco)}</strong></td><td><small>{date(x.atualizado_em)}</small></td></tr>)}</tbody></table></div></section></main>
}
